#!/usr/bin/env python2
# -*- mode: python -*- 
import sys
import time

import repubsub
from helpers import random_tags, green

speed = 0.0 if sys.argv[1:] else 0.7

# Create an exchange connection
exchange = repubsub.Exchange('comicbook_tags', port=28015, host='localhost')
    
while True:
    # Create a random topic and payload
    tags, payload = random_tags()

    # Print out what we're publishing
    print ' '.join(tags)
    print '\t:', green(payload)

    # publish what we're publishing
    exchange.topic(tags).publish(payload)

    # wait for a bit
    time.sleep(speed)
