#!/usr/bin/env python2
import sys
import time

import repubsub
from helpers import random_tags, green, get_speed


# Figure out how fast to run this thing
speed = get_speed(sys.argv)

# Create an exchange connection
exchange = repubsub.Exchange('comicbook_tags', port=28015, host='localhost')
    
while True:
    # Create a random topic and payload
    tags, payload = random_tags()

    # Print out what we're publishing
    print ' '.join(tags)
    print '\t:', green(payload)

    # publish what we're publishing
    exchange.topic(tags).publish(payload)

    # wait for a bit
    time.sleep(speed)
