#!/usr/bin/env python2

import sys

import repubsub
from helpers import highlight_matching_tags, green

if __name__ == '__main__':

    # Parse the commandline args into tags
    tags = sys.argv[1].split()

    # Connect to the exchange
    exchange = repubsub.Exchange(
        'comicbook_tags',
        port=28015,
        host='localhost'
    )

    # Set up the ReQL filter based on our tags
    def reql_filter(topic):
        return topic.contains(*tags)

    # Create the queue that will receive the messages
    queue = exchange.queue(reql_filter)

    # Subscribe to the queue and print the messages as they arrive
    for topic_tags, payload in queue.subscription():
        print highlight_matching_tags(tags, topic_tags)
        print '\t:', green(payload)
