#!/usr/bin/env python2

import sys

import repubsub
from helpers import highlight_matching_tags, green

if __name__ == '__main__':

    # Parse the commandline into two groups of tags
    tags1, tags2 = sys.argv[1].split(' and ')
    tags1 = tags1.split(' or ')
    tags2 = tags2.split(' or ')
    all_tags = tags1 + tags2

    # Connect to the exchange
    exchange = repubsub.Exchange(
        'comicbook_tags',
        port=28015,
        host='localhost'
    )

    # Set up the ReQL filter based on our tags
    def reql_filter(topic):
        contains_tags1 = topic.set_intersection(tags1) != []
        contains_tags2 = topic.set_intersection(tags2) != []
        return contains_tags1 & contains_tags2

    # Create the queue that will receive the messages
    queue = exchange.queue(reql_filter)

    # Subscribe to the queue and print the messages as they arrive
    for topic_tags, payload in queue.subscription():
        print highlight_matching_tags(all_tags, topic_tags)
        print '\t:', green(payload)
